# Generated by Django 5.2.8 on 2025-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("isbn", models.CharField(blank=True, max_length=13)),
                (
                    "published_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
