# Generated by Django 5.2.8 on 2025-12-08 03:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("purchase", "Purchase"),
                            ("upload", "Upload"),
                            ("comment", "Comment"),
                            ("update", "Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("icon", models.CharField(default="chart", max_length=50)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
