"""
Django settings for fision project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import tempfile

from django.core.exceptions import ImproperlyConfigured

from wireview.schemas import AutoBroadcast

up = os.path.dirname

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = up(up(os.path.abspath(__file__)))


WIREVIEW = {
    "BOOST_PAGES": True,
    "AUTO_BROADCAST": AutoBroadcast(
        model=True,
        model_pk=True,
        related=True,
        m2m=True,
        # The models the examples and fixtures subscribe to. Nothing else is broadcast.
        senders={
            ("bookmarks", "Bookmark"),
            ("chat", "Message"),
            ("dashboard", "Activity"),
            ("dashboard", "Stat"),
            ("notifications", "Notification"),
            ("poll", "Option"),
            ("quiz", "Submission"),
            ("rating", "Product"),
            ("rating", "Rating"),
            ("todo", "Item"),
        },
    ),
    # Enable sync/async transition detection in development
    "DEBUG_SYNC_TRANSITIONS": True,
    "DEBUG_SYNC_TRANSITIONS_WARNING_THRESHOLD": 2,
    "DEBUG_SYNC_TRANSITIONS_ERROR_THRESHOLD": 3,
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "b7!j@8gk-vdq3tona^(i(qg#xiir*%r-@u1f&fw@@(ccwy^ijb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "examples.todo",
    "examples.chat",
    "examples.dashboard",
    "examples.poll",
    "examples.rating",
    "examples.search",
    "examples.quiz",
    "examples.notifications",
    "examples.slots",
    "examples.livecomp",
    "examples.hooks",
    "testproj.bookmarks",
    "testproj.livesession",
    "testproj.uploadprobe",
    "testproj.listprobe",
    "testproj.cspprobe",
    "testproj.valueprobe",
    "testproj.errorprobe",
    "testproj.jsprobe",
    "testproj.formprobe",
    "testproj.fileprobe",
    "testproj.streamprobe",
    "testproj.offlineprobe",
    "testproj.hookprobe",
    "testproj.tempprobe",
    "testproj.slotprobe",
    "testproj.stickyprobe",
    "testproj.deadprobe",
    "testproj.inheritprobe",
    "wireview",
    "channels",
    "daphne",
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # No WhiteNoise middleware: static files are served by asgi.py's ASGIStaticFilesHandler.
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "testproj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "testproj.wsgi.application"
ASGI_APPLICATION = "testproj.asgi.application"

# Channel layer. WIREVIEW_TEST_LAYER picks it: memory (default), nats or redis.
#   memory -> no broker to run, single process only. The default so that the unit and
#             integration suite never needs one: a few tests (UploadView) do reach the
#             layer, and pointing them at an absent broker costs two minutes in connect
#             timeouts. `make test` therefore stays on memory.
#   nats   -> nats-server on NATS_URL (channels-nats). The layer the project targets;
#             `make test-e2e` and the deployment recipes use it.
#   redis  -> redis-server on REDIS_URL (channels_redis). CI's E2E runs on it as well as
#             on nats (docs/COMPATIBILITY.md, #130); locally `make test-e2e LAYER=redis`.
_LAYER = os.environ.get("WIREVIEW_TEST_LAYER", "memory")
if _LAYER == "nats":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_nats.NatsChannelLayer",
            "CONFIG": {"servers": [os.environ.get("NATS_URL", "nats://127.0.0.1:4222")]},
        },
    }
elif _LAYER == "redis":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379")]},
        },
    }
elif _LAYER == "memory":
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
else:
    raise ImproperlyConfigured(f"WIREVIEW_TEST_LAYER must be nats, redis or memory, not {_LAYER!r}")

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        "ATOMIC_REQUESTS": True,
        "OPTIONS": {
            "timeout": 20,
        },
        "TEST": {
            # One file per test process. A fixed name let two runs in the same checkout
            # create, flush and drop each other's database, and the result read as a
            # flaky suite: "readonly database", "no such table", a different count each
            # time (#125). A file rather than SQLite's memory database because the E2E
            # server answers from its own thread and has to see the same data.
            "NAME": os.path.join(tempfile.gettempdir(), f"wireview-test-{os.getpid()}.sqlite3"),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
    },
    "formatters": {
        "django.server": {
            "()": "wireview.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        }
    },
    "loggers": {
        "wireview": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "wireview.sync_detector": {
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}
